### ISSUE TITLE
Add `.allSettled()` method

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/p-progress#10]
Like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

**Comment by Richienb** [comment]
Before adding this, is it possible to simplify the types so that `.all` doesn't require 10 separate definitions?

**Comment by sindresorhus** [comment]
That would be nice, but I'm not sure if it's possible. TypeScript did receive variadic tuple support, but not sure if it solves all the same problems or whether it's as type safe.

- https://github.com/microsoft/TypeScript/issues/5453
- https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#variadic-tuple-types

**Comment by privatenumber** [comment]
This one is a little more complicated but I think it should be possible. Precedent in p-all: https://github.com/sindresorhus/p-all/pull/9

**Comment by Richienb** [comment]
Reworking those typings for Iterables like `Set`s might be a challenge because of how `P in keyof Task` may yield `get`, `set`, `has`, etc. instead of the indexes we want.
