### ISSUE TITLE
Rework API to target async/await interfaces

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/p-progress#18]
Instead of doing this:

```js
const progressPromise = new PProgress((resolve, reject, progress) => {
	const job = new Job();

	job.on('data', data => {
		progress(data.length / job.totalSize);
	});

	job.on('finish', resolve);
	job.on('error', reject);
});
```

The API could instead be reworked to do this:

```js
const progressPromise = pProgress(async progress => {
	const job = new Job();

	job.on('data', data => {
		progress(data.length / job.totalSize);
	});

	job.on('error', error => {
		throw error
	});

	return await pEvent(job, 'finish')
})
```

With the legacy `Promise` interface working like this:

```js
const progressPromise = pProgress(progress => new Promise((resolve, reject) => {
	const job = new Job();

	job.on('data', data => {
		progress(data.length / job.totalSize);
	});

	job.on('finish', resolve);
	job.on('error', reject);
}))
```

It looks like `PProgress.fn` already does something similar but you still have to invoke the returned function:

https://github.com/sindresorhus/p-progress/blob/e63f3becd8f4d83e28b868920d1e3084b7091344/index.js#L36-L65

**Comment by sindresorhus** [comment]
The `new PProgress` version was meant to integrate with callback/event APIs.

Why is `PProgress.fn` not good enough?

**Comment by Richienb** [comment]
The issue I have with `PProgress.fn` is that after defining the function, I still have to invoke it. To write drier code, I don't want to have to do that.

**Comment by sindresorhus** [comment]
Alright. Let's make the main export use the promise way. I still like to keep `new PProgress` under a property though.

**Comment by Richienb** [comment]
`pProgress.Instance`?

**Comment by sindresorhus** [comment]
> pProgress.Instance?

👍
