### ISSUE TITLE
Reported percentage is lower than the last

### ISSUE THREAD

**Issue by revelt** [sindresorhus/p-progress#8]
Recently there were updates somewhere and suddenly one of my [CLI](https://www.npmjs.com/package/update-versions)'s stopped working because `p-progress` threw an error complaining that the reported percentage is lower than the last reported:

https://github.com/sindresorhus/p-progress/blob/a24163f30888e2337ddfcd1fc74eb0ed7973167c/index.js#L78-L86
I edited `p-progress` right in `node_modules` and simply commenting out the throw solves the problem, that case `progress < this._progress` can be ignored:

https://github.com/sindresorhus/p-progress/blob/a24163f30888e2337ddfcd1fc74eb0ed7973167c/index.js#L83

## Idea

What if we changed it to do nothing if no bigger progress is reported (no matter it's smaller or equal than previous):

```js
if (progress <= this._progress) {
	return;
}

this._progress = progress;
```

App would just skip unacceptable values until a bigger value is reported. Currently, API seems too strict.

What do you think?

**Comment by sindresorhus** [comment]
Why are you giving it smaller values than previously? It's always easier to come up with an elegant solution when I know your use-case instead of just the problem.

**Comment by revelt** [comment]
> Why are you giving it smaller values than previously?

To my best understanding, smaller values should _not_ come, I'm p-mapping over pacote's results... It's definitely not intentional :)

**Comment by timlesallen** [comment]
@sindresorhus I'm hitting this same problem, running in a browser, generally after you tab away and come back.  My best guess is that event handlers are all firing at once when you come back to the tab, and that order is _not_ guaranteed.  I would vote to remove the `throw` (and just not update the value) here as it's messing with our exception reporting (I can't really find away to catch these as they are out of context).

Loving `p-progress` - thanks!

**Comment by sindresorhus** [comment]
> To my best understanding, smaller values should not come, I'm p-mapping over pacote's results... It's definitely not intentional :)

Are you using the `index` argument? If so, that's definitely wrong if `p-map` is run without setting the `concurrency` option to `1`.

**Comment by sindresorhus** [comment]
I kinda regret the "passing in percentage" interface. It would have been better to accept a `totalUnitCount` upfront and then have it accept a `unitCount` parameter. Then there would be no chance of getting a regressed percentage as it would be calculated for you.

**Comment by revelt** [comment]
> Are you using the index argument?

No.

@sindresorhus if you feel uneasy about MR #9 feel free to close this issue and that ninth PR, no hurt feelings. I'm grateful for all your libraries, let's concentrate on features and serious issue tickets instead. Feel free to close this issue.

**Comment by sindresorhus** [comment]
No-no, I'm fine with lifting that restriction. You're right it's not important enough to reject the promise.

**Comment by sindresorhus** [comment]
Regarding https://github.com/sindresorhus/p-progress/issues/8#issuecomment-586736127. I posted some thoughts in https://github.com/sindresorhus/p-progress/issues/1#issuecomment-586739461.
